### ISSUE TITLE
Add custom RPC parameter

### ISSUE THREAD

**Issue by elliotBraem** [NEARBuilders/near-bos-webcomponent#7]
For context, this [post](https://near.social/mob.near/widget/MainPage.N.Post.Page?accountId=efiz.near&blockHeight=115257294) and then [comment](https://near.social/mob.near/widget/MainPage.N.Comment.Page?accountId=petersalomonsen.near&blockHeight=115381935)

Fast Near was enabled on near.social gateway via this [change here](https://github.com/NearSocial/viewer/commit/cf7c43376ab4d247af42576b2cbabf38f1ac9f4b), line 97 -- Could we pass RPC the same way here?

**Comment by petersalomonsen** [comment]
Yes we should!

**Comment by klngrs** [comment]
In the example [here](https://near.social/mob.near/widget/MainPage.N.Post.Page?accountId=efiz.near&blockHeight=115257294), window.location is used to determine whether to proxy, which exists as part of the runtime environment. 

In our case, we'd want to pass that setting from the CLI which would mean some method of getting the rpc setting from the bos-workspace build script to the gateway's runtime code, correct? Which is independent of the gateway build (I was using nwc as a gateway). So you'd almost need to set a window rpc variable as part of the transpiling process bos-workspace does on the app file, right? 

Am I thinking about this correctly?

**Comment by elliotBraem** [comment]
@klngrs yeah that's a bit confusing, but it used window.location because I believe fast near is working on a paid/private RPC service (see [tweet](https://x.com/ekuzyakov/status/1771610351311745083?s=20)) -- when I updated bos-workspace to use lava rpc this past week, I only needed to set it in the `config` param [here](https://github.com/NEARBuilders/bos-workspace/blob/16e9f0418974a5f335cb108f077c6575dc682484/gateway/src/useAuth.js#L80). 

And I believe this config param can be updated in runtime, multiple sites allow you to toggle the RPC (checkout the bottom right of [ref.finance](https://app.ref.finance/)).

I think we could pass it to the web component like: 
`<near-social-viewer src={...} rpc={RPC_URL} />`

And in dev, we know the rpc url is going to be from bos-workspace `localhost:8080`, or whatever port was configured. 

But I don't really know the best way to determine when in dev vs prod... maybe we start with just adding a toggle [here](https://github.com/NEARBuilders/near-bos-webcomponent/blob/main/public/index.html). Any ideas here?


Side note... as another example/use case, I was messing with this other repo the other day. I added near-bos-wc script tags to index.html [here](https://github.com/elliotBraem/orionreed.com/blob/bbe86fe49312003f2b6ab8367c0587bad701b0f7/index.html#L16), and then I used the web component [here](https://github.com/elliotBraem/orionreed.com/blob/bbe86fe49312003f2b6ab8367c0587bad701b0f7/src/App.tsx#L70). I installed bos-workspace because I wanted to locally develop these widgets, too, but didn't want to configure all the redirect map stuff...
